language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jamesw201/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jamesw201/docker-react npm run test