sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jamesw201/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jamesw201/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-955869261654"
    bucket_path: "docker-react"
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    skip_cleanup: true